# Generated by Django 5.2 on 2025-04-08 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_orders_delete_projectmanager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Address',
        ),
    ]
