# Generated by Django 5.2 on 2025-04-08 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_orders_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Name',
            new_name='Product',
        ),
    ]
