# Generated by Django 5.2 on 2025-04-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_name_orders_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Product',
            new_name='Name',
        ),
    ]
