# Generated by Django 5.2 on 2025-04-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_product_orders_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
