# Generated by Django 5.2 on 2025-04-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
