# Generated by Django 5.2 on 2025-04-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
